name: Run Azure Login with OpenID Connect and PowerShell
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
      id-token: write
      contents: read
      checks: write
      
jobs: 
  oidclogin:
      runs-on: ubuntu-latest
      steps:
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

        - name: 'List resource groups'
          run: az group list
